CFLAGS= -Wall -Wextra -std=c99

BIND     = libbind-6.0
BIND_TGZ = ${BIND}.tar.gz
BIND_URL = http://ftp.isc.org/isc/libbind/cur/${BIND_TGZ}
RES_A    = ${BIND}/libbind.a
RES_I    = ${BIND}/include

dns-notifyd: dns-notifyd.c ${RES_A}
	${CC} ${CFLAGS} -I${RES_I} -o dns-notifyd dns-notifyd.c ${RES_A}

clean:
	rm -rf dns-notifyd ${BIND}

${RES_A}: ${BIND_TGZ}
	tar xf ${BIND_TGZ}
	cd ${BIND} && ./configure && make all

${BIND_TGZ}:
	curl -O ${BIND_URL}
