.Dd January 18, 2022
.Dt NSNOTIFY 1 "DNS Commands Manual"
.Os DNS
.Sh NAME
.Nm nsnotify
.Nd send DNS NOTIFY messages
.Sh SYNOPSIS
.Nm
.Op Fl 46dtV
.Op Fl p Ar port
.Aq Ar zone
.Ao Ar target Ac Ns ...
.Nm
.Op Fl 46dtV
.Op Fl p Ar port
.Fl F Ar zones
.Ao Ar target Ac Ns ...
.Nm
.Op Fl 46dtV
.Op Fl p Ar port
.Fl f Ar targets
.Ao Ar zones Ac Ns ...
.Nm
.Op Fl 46dtV
.Op Fl p Ar port
.Fl F Ar zones
.Fl f Ar targets
.Sh DESCRIPTION
The
.Nm
program
sends DNS NOTIFY messages for a list of
.Ar zone Ns s
to a list of
.Ar target Ns s .
You can either provide a list of
.Ar target Ns s
on the command line,
or use the
.Fl f Ar targets
option to read from a file.
To send a notifications about more than one zone,
you can use the
.Fl F Ar zones
option to read from a file.
.Pp
Note:
.Nm nsnotify
(without
.Ql d )
is a client for sending DNS NOTIFY messages
whereas
.Nm nsnotifyd
(with
.Ql d )
is a daemon for handling DNS NOTIFY messages.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl 4
Use IPv4 only
(apart the system resolver).
.It Fl 6
Use IPv6 only
(apart the system resolver).
.It Fl d
Debugging mode.
.Pp
Use once to print successful message sends.
.Pp
Use twice to get dumps of DNS packets.
.It Fl F Ar zones
File containing list of zones
to send NOTIFY messages about.
There must be one domain name per line,
with no comments or extra white space.
.Pp
If
.Ar zones
is
.Ql -
then the domain names are read from
.Li stdin .
.It Fl f Ar targets
File containing list of addresses
to send NOTIFY messages to.
There must be one target address per line,
with no comments or extra white space.
.Pp
If
.Ar targets
is
.Ql -
then the addresses are read from
.Li stdin .
.It Fl p Ar port
Connect to
.Ar port ,
which may be a service name or a port number.
The default is the
.Sy domain
service, port 53.
.It Fl t
Make TCP connections instead of using UDP.
.It Fl V
Print details about this version of
.Nm .
.El
.Sh SEE ALSO
.Xr nsnotifyd 1 .
.Sh AUTHOR
.An Tony Finch
.Aq Li dot@dotat.at
.Aq Li fanf2@cam.ac.uk
.br
at Cambridge University Information Services
.\" You may do anything with this. It has no warranty.
.\" http://creativecommons.org/publicdomain/zero/1.0/
