#!/bin/sh
(	zone=$1 serial=$2 master=${3:+@$3}
	case $zone in
	(.) zone=root
	esac
	dig +noall +answer +onesoa +multiline $master $zone axfr >$zone
	git commit -q -m "$zone IN SOA $serial" $zone
) 2>&1 |
logger -p daemon.notice -t nsnotify2git -s
