.Dd June 9, 2015
.Dt NSNOTIFYD 1 "DNS Commands Manual"
.Os DNS
.Sh NAME
.Nm nsnotifyd
.Nd handle DNS NOTIFY messages by running a command
.Sh SYNOPSIS
.Nm
.Op Fl 46d
.Op Fl l Ar facility
.Op Fl P Ar pidfile
.Op Fl u Ar user
.Op Fl s Ar authority
.Op Fl a Ar addr
.Op Fl p Ar port
.Aq Ar command
.Ao Ar zone Ac Ns ...
.Sh DESCRIPTION
The
.Nm
daemon
monitors a set of DNS
.Ar zone Ns s
and runs a
.Ar command
when any of them change.
It listens for DNS NOTIFY messages
so it can respond to changes promptly.
It also uses each zone's SOA refresh and retry parameters
to poll for updates if
.Nm
does not receive NOTIFY messages more frequently.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl 4
Use IPv4 only
(apart from DNS queries made using the system resolver configuration).
.It Fl 6
Use IPv6 only
(apart from DNS queries made using the system resolver configuration).
.It Fl a Ar address
Listen on
.Ar address
for NOTIFY messages.
The default is
.Li 127.0.0.1 .
.Pp
You can specify an IP address or hostname.
A hostname is looked up using the system resolver.
If it resolves to multiple addresses then one
arbitrary address is chosen,
constrained by the
.Fl 4
or
.Fl 6
options.
.It Fl d
Debugging mode.
.Pp
Use once to prevent
.Nm
from daemonizing
and to make it print log messages to stderr.
.Pp
Use twice to get dumps of DNS packets.
.It Fl l Ar facility
Set the
.Xr syslog 3
facility.
The default is
.Sy daemon .
.It Fl P Ar path
Write the
.Nm
PID to the given
.Ar path
after daemonizing
and before dropping privilege.
.It Fl p Ar port
Listen on
.Ar port ,
which may be a service name or a UDP port number.
The default is the
.Sy domain
service, UDP port 53.
.It Fl s Ar authority
Specify an authoritative server to
use for zone SOA refresh queries.
By default
.Nm
does periodic refreshes
using the system recursive resolver,
so its refresh queries may get stale cached answers.
.Pp
You can specify an IP address or hostname.
A hostname is looked up using the system resolver,
constrained by the
.Fl 4
or
.Fl 6
options.
.It Fl u Ar user
Drop privilege to
.Ar user
after daemonizing.
.El
.Sh DETAILS
.Ss Startup
Before daemonizing,
.Nm
makes SOA queries for each
.Ar zone
to initialize its refresh and retry timers.
.Pp
Daemonizing is configured using the
.Fl P
.Ar pidfile
and
.Fl u
.Ar user
options,
or disabled with the
.Fl d
debugging option.
.Pp
When daemonizing,
.Nm
does
.Em not
change its working directory.
This allows the
.Ar command
to be context-sensitive.
.Ss Server
The
.Nm
daemon acts as a very simple UDP-only DNS server.
The only DNS queries handled by
.Nm
are NOTIFY messages for
.Ar zones
given on the command line.
Other queries are rejected with a
.Sy REFUSED
response code, or
.Sy FORMERR
if the query is too mangled.
.Ss Zone refresh process
When
.Nm
receives a NOTIFY,
or when a refresh or retry timer expires,
it makes a SOA query to see if the zone has changed.
The SOA query is sent to the source of the NOTIFY
or, if a timer expired, to the server given in the
.Fl s
option.
.Pp
When the SOA reply indicates the zone's serial number has increased,
.Nm
runs the
.Ar command
with two or three arguments:
.Bl -enum
.It
the
.Ar zone
name;
.It
its new serial number;
.It
the source address of the NOTIFY,
or no third argument if the update was found via a periodic refresh or retry.
.El
.Pp
When the command exits successfully,
.Nm
updates its copy of the zone's SOA parameters.
It will then poll the zone on its refresh interval.
.Pp
If the SOA query or command fails,
.Nm
does not update its SOA parameters,
and polls the zone on its retry interval.
.Sh EXAMPLE
Say you have a zone,
.Sy example.org ,
which is updated dynamically,
and you want to automatically record its history in a
.Xr git 1
repository.
.Ss Setup git
On a server that is authoritative for
.Sy example.org ,
run the following commands:
.Bd -literal -offset indent
$ mkdir zone-history
$ cd zone-history
$ git init
$ touch example.org
$ git add example.org
$ git commit -m 'add example.org (empty)'
.Ed
.Ss Monitor the zone
The
.Nm nsnotify2git
script is designed to work with
.Nm
to record the history of a set of zones.
Continuing the transcript,
.Bd -literal -offset indent
$ nsnotifyd -P .nsnotifyd.pid -p 5533 nsnotify2git *
.Ed
.Ss Send notifies
To configure BIND to send notifies to
.Nm ,
so it detects changes more efficiently,
look in your
.Xr named.conf 5
file for
.Bd -literal -offset indent
zone example.org {
    ...
};
.Ed
.Pp
Inside the zone clause,
add or modify the
.Ql also-notify
setting so it includes the address and port used by
.Nm ,
like
.Bd -literal -offset indent
also-notify { 127.0.0.1 port 5533; };
.Ed
.Ss Update the zone
Now, when the zone changes,
.Nm
will quickly record the change in your
.Xr git
repository.
.Bd -literal -offset indent
$ nsupdate -l
> add example.com 3600 IN TXT "foo"
> send
> quit
$ git log --format=%s
example.org IN SOA 1234
add example.org (empty)
.Ed
.Sh BUGS
The
.Nm
daemon is not very secure.
.Pp
It accepts any well-formed NOTIFY message,
regardless of the source.
It does not support TSIG authentication (RFC 2845)
for access control.
.Pp
The
.Nm
daemon
only handles one query at a time,
which prevents it from becoming a fork bomb.
However, you can easily overwhelm it
with more notifications than it can handle.
A spoofed NOTIFY will make
.Nm
send a SOA query to the spoofed source address
and wait for a reply (which will probably not arrive),
during which time it is unresponsive.
.Pp
You should configure
.Nm
to listen on a loopback address
(which is the default)
or use a packet filter to block unwanted traffic.
.Pp
The
.Nm
daemon
is not aware of the authoritative servers for a zone,
so it cannot filter spurious NOTIFY messages.
It has a very simplistic mechanism
for choosing which servers to query when refreshing a zone.
.Pp
The
.Nm
daemon cannot accept NOTIFY messages over TCP (RFC 5966).
It does not support EDNS (RFC 6891).
However,
NOTIFY messages and responses are very small,
so following these specifications should not be necessary in practice.
.Sh SEE ALSO
.Xr git 1 ,
.Xr named 8 ,
.Xr named.conf 5 ,
.Xr syslog 3 .
.Rs
.%A Paul Mockapetris
.%T Domain names - concepts and facilities
.%R RFC 1034
.%D November 1987
.Re
.Rs
.%A Paul Mockapetris
.%T Domain names - implementation and specification
.%R RFC 1035
.%D November 1987
.Re
.Rs
.%A Robert Elz
.%A Randy Bush
.%T Serial number arithmetic
.%R RFC 1982
.%D August 1996
.Re
.Rs
.%A Paul Vixie
.%T A mechanism for prompt notification of zone changes (DNS NOTIFY)
.%R RFC 1996
.%D August 1996
.Re
.Sh AUTHOR
.An Tony Finch
.Aq Li dot@dotat.at
.Aq Li fanf2@cam.ac.uk
.br
at Cambridge University Information Services
.\" You may do anything with this. It has no warranty.
.\" http://creativecommons.org/publicdomain/zero/1.0/
