#!/bin/sh
#
# SPDX-License-Identifier: 0BSD OR MIT-0

(	zone=$1 serial=$2 master=${3:+@$3}
	nsdiff="-m $master $zone"
	nsupdate="-l"
	nspatch -- $nsdiff -- $nsupdate
) 2>&1 |
logger -p daemon.notice -t nsnotify2update -s
