.Dd June 9, 2015
.Dt NSNOTIFYD 1 "DNS Commands Manual"
.Os DNS
.Sh NAME
.Nm nsnotifyd
.Nd handle DNS NOTIFY messages by running a command
.Sh SYNOPSIS
.Nm
.Op Fl 46d
.Op Fl l Ar facility
.Op Fl P Ar pidfile
.Op Fl u Ar user
.Op Fl s Ar authority
.Op Fl a Ar addr
.Op Fl p Ar port
.Aq Ar command
.Ao Ar zone Ac Ns ...
.Sh DESCRIPTION
The
.Nm
daemon
monitors a set of DNS zones
and runs a command when any of them change.
It listens for DNS NOTIFY messages
so it can respond to changes promptly.
It also uses the zone SOA refresh and retry parameters
to poll for updates if it does not receive any NOTIFY messages.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl 4
.It Fl 6
.It Fl d
.It Fl l Ar facility
.It Fl P Ar pidfile
.It Fl p Ar port
.It Fl s Ar authority
.It Fl u Ar user
.El
.Sh BUGS
The
.Nm
daemon is not very secure.
.Pp
It accepts any well-formed NOTIFY message,
regardless of the source.
It does not support TSIG authentication (RFC 2845)
for access control.
It is easy to flood
.Nm
with more notifications than it can handle.
.Pp
You should configure it to listen on a loopback address
(which is the default)
or use a packet filter to block unwanted traffic.
.Pp
The
.Nm
daemon
is not aware of the authoritative servers for a zone,
so it cannot filter spurious NOTIFY messages.
It has a very simplistic mechanism
for choosing which servers to query when refreshing a zone.
.Pp
The
.Nm
daemon cannot accept NOTIFY messages over TCP.
(It does not conform to RFC 5966.)
It does not support EDNS (RFC 6891).
However,
NOTIFY messages and responses are very small,
so following these specifications should not be necessary in practice.
.Sh NON-BUGS
It only handles one query at a time,
which prevents it from becoming a fork bomb.
.Pp
It cannot be used to amplify spoofed UDP packets.
.Sh SEE ALSO
.Xr named 8 ,
.Xr named.conf 5 .
.Rs
.%A Paul Mockapetris
.%T Domain names - concepts and facilities
.%R RFC 1034
.%D November 1987
.Re
.Rs
.%A Paul Mockapetris
.%T Domain names - implementation and specification
.%R RFC 1035
.%D November 1987
.Re
.Rs
.%A Robert Elz
.%A Randy Bush
.%T Serial number arithmetic
.%R RFC 1982
.%D August 1996
.Re
.Rs
.%A Paul Vixie
.%T A mechanism for prompt notification of zone changes (DNS NOTIFY)
.%R RFC 1996
.%D August 1996
.Re
.Sh AUTHOR
.An Tony Finch
.Aq Li dot@dotat.at
.Aq Li fanf2@cam.ac.uk
.br
at Cambridge University Information Services
.\" You may do anything with this. It has no warranty.
.\" http://creativecommons.org/publicdomain/zero/1.0/
